name: Grok Update
on:
  issue_comment:
    types: [created]
jobs:
  update:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, 'Grok, update')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Pull grok-edits
        run: |
          git fetch origin grok-edits
          git checkout grok-edits
          git pull origin grok-edits --rebase || true  # Pull, ignore if branch is new
      - name: Apply Grok Changes
        run: |
          echo "Manual step: Copy Grok’s code from comment into files"
          echo "Grok was here $(date)" > grok-test.txt
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Grok’s updates"
          branch: grok-edits
          create_branch: true
