name: Grok Update
on:
  issue_comment:
    types: [created]
jobs:
  update:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, 'Grok, update')
    steps:
      - uses: actions/checkout@v3
      - name: Apply Grok Changes
        run: |
          echo "Manual step: Copy Grok’s code from comment into files"
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Grok’s updates"
          branch: grok-edits